apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: default
  labels:
    app: compliance-service
    version: v1
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: compliance-service
  ports:
  - name: http
    protocol: TCP
    port: 8018
    targetPort: http
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: metrics
  sessionAffinity: None
